# Generated by Django 3.1.5 on 2021-04-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Forum',
        ),
    ]
